### ISSUE TITLE
MySQL vs MariaDB

### ISSUE THREAD

**Issue by NeodarZ** [NeodarZ/NeoKron-Projekt#10]
Problème de comptabilité entre les deux types de base de données. 
mysql_query("SET NAMES UTF8") => pause problème !

**Comment by NeodarZ** [comment]
Résolu partiellement, on doit trouver une solution pour l'UTF8 avec MySQL.

**Comment by NeodarZ** [comment]
Passage de MySQL vers MariaDB sur le serveur de démo, le bug de l'UTF8 est résolu ! Reste plus qu'a le résoudre sur le serveur du lycée !

**Comment by NeodarZ** [comment]
Je ferme l'issue car le serveur du lycée n'est plus accessible.

**Comment by Redkro** [comment]
Ok pas d soucis ca va le bts ?
Le 20 juil. 2016 11:46, "Corentin BRETON" <notifications@github.com> a
écrit :

**Comment by NeodarZ** [comment]
Yep tous va bien mais je pense pas qu'en parler ici soit adapter mais bon ^^
